### ISSUE TITLE
Approving a cleared employee's SWTD

### ISSUE THREAD

**Issue by gilberx** [ArchonsDev/react-pointwatch-web#101]
Maka approve ba ang head bisag clear na ang employee? basig pwede ra diay niya ga buot buot ko ani nga issue.
![image](https://github.com/user-attachments/assets/16496df8-228e-4a2f-9f41-0515a8699dc6)
![image](https://github.com/user-attachments/assets/71648b84-d081-47f9-af9a-3a37974e3775)
![image](https://github.com/user-attachments/assets/4d9bdef9-8a32-4c7c-adb4-118c8eb79658)

**Comment by mssjcksn** [comment]
I don't know if this is classified as an issue—I don't think it matters for this situation, no? 

I believe the head can grant clearance ra gihapon for the sake of the deadline or something and continue to approve ra gihapon.

@cxrvxxxx pls confirm thanks

@gilberx does this affect the point calculation ba?

**Comment by gilberx** [comment]
Sa point calculation kay ang excess points kay di ma add same ra gihapon pag clear

**Comment by gilberx** [comment]
So maka add gihapon og SWTD bisag na end na ang Semester sa?

**Comment by mssjcksn** [comment]
> Sa point calculation kay ang excess points kay di ma add same ra gihapon pag clear 

approve swtd of a cleared emp > doesnt change point calc? 

sakto ba

**Comment by gilberx** [comment]
![image](https://github.com/user-attachments/assets/8894bbe0-bfb9-47b9-8c20-b1a71559f1ce)
 mo ing-ani ra ay if mo approved kog SWTD sa cleared employee mo add ang Current Points pero dili sa Excess points
