### ISSUE TITLE
Found Issues

### ISSUE THREAD

**Issue by cxrvxxxx** [ArchonsDev/react-pointwatch-web#32]
## In Admin Dashboard

1. `Point Balance` not updating after clearing an Employee in /dashboard/\<id>
![image](https://github.com/ArchonsDev/react-pointwatch-web/assets/35297070/91e5b0b8-d55d-4cf4-bdba-c1cd18be4222)

2. `Points` column name should be changed to `Point Balance` or something more appropriate.
![image](https://github.com/ArchonsDev/react-pointwatch-web/assets/35297070/64eb5543-def1-4cae-91f7-912317e752a6)

## While editing SWTD

Date can be set to values that exceed the term start/end date boundaries. (This affects point calculation)
![image](https://github.com/ArchonsDev/react-pointwatch-web/assets/35297070/657b2b9d-085e-4c77-9588-da4402ecbfa6)
* For ongoing terms, max date should be current date, otherwise, max should be the term end date.

**Comment by mssjcksn** [comment]
# [THIS COST ME MY SANITY BUT HEY ITS FIXED](https://github.com/ArchonsDev/react-pointwatch-web/pull/33) 🤩
