### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by shinwoniee** [ArchonsDev/react-pointwatch-web#39]
No error notification appears when inputting an existing email.

![image](https://github.com/ArchonsDev/react-pointwatch-web/assets/147154719/15ffdd6f-f674-4580-9ca9-cbb3561bb4a5)

**Comment by mssjcksn** [comment]
The toast message doesn't show bc the error handler line in the API is commented out found in [api/__init__.py](https://github.com/ArchonsDev/flask-pointwatch-api/blob/qa/api/__init__.py)
@cxrvxxxx pls dont forget to remove that HAHAHHA
![image](https://github.com/ArchonsDev/react-pointwatch-web/assets/62651994/24dd2303-2879-4359-8cb6-d6584e0c26f5)
