### ISSUE TITLE
Disable "Add New Record" button when an Employee is cleared for the Term

### ISSUE THREAD

**Issue by cxrvxxxx** [ArchonsDev/react-pointwatch-web#44]
![image](https://github.com/ArchonsDev/react-pointwatch-web/assets/35297070/a9f4ad71-d668-4cf6-b34a-8a6c59c0bf83)

**Comment by mssjcksn** [comment]
i asked you about this and you said ayaw lang. make up ur mind

**Comment by mssjcksn** [comment]
Disabling this button when certain terms are selected does not make sense to me bc selecting a term does not affect the adding of new record. Instead, I've added validation checks when adding/editing SWTDs. The submit/save changes buttons are also disabled when this error appears. -- #45
