### ISSUE TITLE
Head Dashboard not loading

### ISSUE THREAD

**Issue by Prets2** [ArchonsDev/react-pointwatch-web#62]
i tried going to the dashboard for head, it does not load

**Comment by Prets2** [comment]
![image](https://github.com/user-attachments/assets/33f8223e-119b-4532-b39f-518240ebb691)

**Comment by Prets2** [comment]
![image](https://github.com/user-attachments/assets/c8c6ef06-7543-40d8-be67-de1e7bc1b722)

**Comment by Prets2** [comment]
![image](https://github.com/user-attachments/assets/4d67f1dd-131f-4d8f-b9e3-f3b15b04812f)

**Comment by mssjcksn** [comment]
@Prets2 This [issue](https://github.com/ArchonsDev/flask-pointwatch-api/issues/121) was solved last week. Are you sure your backend (dev branch) is updated? Solving this issue would probably also solve your other [issue](https://github.com/ArchonsDev/react-pointwatch-web/issues/61).

**Comment by mssjcksn** [comment]
@Prets2 
fixed this issue; refer to the recent [commit](https://github.com/ArchonsDev/react-pointwatch-web/commit/9d56b1c3602416f9a3dddd8426df6cc656bf95ec). pull from the points branch and verify

**Comment by owembii** [comment]
bruh im just gon close this lol
