### ISSUE TITLE
Employee Dashboard: Incorrect Pending SWTD Calculations

### ISSUE THREAD

**Issue by gilberx** [ArchonsDev/react-pointwatch-web#64]
Nihimo ko og 3 ka SWTDs sa Academic Year 2024 niya 1 sa Academic Year 2025 niya all of the SWTDs are pending. Pero pag filter nakog Academic Year 2024 ni show og Pending SWTDs: 4.
![image](https://github.com/user-attachments/assets/013f260c-4ae3-497f-8db5-cc3ab2feb66c)

**Comment by gilberx** [comment]
Same issue sa Approved SWTDs og SWTDs For Revision nga cards.

**Comment by owembii** [comment]
@gilberx
Pull from wip branch and verify the fix for the issues you posted. Thanks! :D
