### ISSUE TITLE
Head Dashboard > Employee#1: Status Rejected

### ISSUE THREAD

**Issue by gilberx** [ArchonsDev/react-pointwatch-web#65]
Head Department Dashboard > Employee#1
Update status "Rejected" to "For Revision"
![image](https://github.com/user-attachments/assets/79819eef-d9b3-44f6-9e12-b212ed2e4c41)

**Comment by mssjcksn** [comment]
@gilberx 
Does it also say "Rejected" for the following:
- Head Dashboard > View All SWTDs > Specific SWTD
- Employee Dashboard > View All SWTDs
- Employee Dashboard > View All SWTDs > Specific SWTD

Can you check?
