### ISSUE TITLE
Points Overview Error: HR Staff

### ISSUE THREAD

**Issue by gilberx** [ArchonsDev/react-pointwatch-web#70]
HR Staff Account:
Adto ko sa Points Overview then mo pislit ko og Department mo error siya after.
![image](https://github.com/user-attachments/assets/7262c633-67e7-4d41-952b-60baa5bfe47f)
![image](https://github.com/user-attachments/assets/24c3f896-55ad-4679-b746-8998fcd61e2c)
![image](https://github.com/user-attachments/assets/323bd76e-4a51-4acb-b60f-bd112a370937)

**Comment by mssjcksn** [comment]
I believe this is the same problem as #74
