### ISSUE TITLE
Department Heads tab on system manage for super user is buggy 

### ISSUE THREAD

**Issue by Prets2** [ArchonsDev/react-pointwatch-web#73]
At the start ok pa ang department heads and i am successful in promoting a head. pero pag after ana kay pag balik nako to add another head for an another department unta kay ni error na sha
![image](https://github.com/user-attachments/assets/4abb7a6c-8cc5-4c47-a266-8c00740fddb3)
![image](https://github.com/user-attachments/assets/10a1ddbd-7f56-414b-8358-1b2ee88980bc)

**Comment by mssjcksn** [comment]
Code wild, it probably hates men. 
Same comment for #74 pls tell me more abt ur situation.
