### ISSUE TITLE
HR Points Overview:

### ISSUE THREAD

**Issue by Prets2** [ArchonsDev/react-pointwatch-web#74]
it works for a split second when i select a department but then an error shows up
![image](https://github.com/user-attachments/assets/7ca5046e-68e8-404e-b8e4-24bbc37483c5)

**Comment by Prets2** [comment]
![image](https://github.com/user-attachments/assets/06536d59-fd97-4092-8dfe-d3a6321c45fa)

**Comment by mssjcksn** [comment]
That's so weird bc it works fine for mine? Can you provide more details of your testing situation? Like what users you have, what departments you've made, if you made any terms, etc.
