### ISSUE TITLE
HR Staff: Points Overview incorrect status

### ISSUE THREAD

**Issue by gilberx** [ArchonsDev/react-pointwatch-web#75]
Ako ge grant clearance ang Employee gamit head(1st image) then ako ge check sa HR Account ang Point overview if Cleared naba siya pero dili(2nd image). Pero if ako e click ang Employee(3rd image) sa Points Overview naka cleared siya didto rajud sa Points Overview.
![image](https://github.com/user-attachments/assets/09a24014-8b5e-4782-83ac-6986927314e9)
![image](https://github.com/user-attachments/assets/c0d65196-e30d-441a-8141-fcebc63f5d4e)
![image](https://github.com/user-attachments/assets/6eeef3bc-fb28-463a-897f-3edfbb20c019)

**Comment by mssjcksn** [comment]
@gilberx 
I tried to replicate the problem pero I don't know what I did wrong? 
Is that in the right semester?
![image](https://github.com/user-attachments/assets/7c57c70f-c5bd-4a09-b685-c9bb39f4a817)
