### ISSUE TITLE
I could not run the front end 

### ISSUE THREAD

**Issue by Prets2** [ArchonsDev/react-pointwatch-web#76]
I pulled from "wips" front end nya dili mo show ang front end
![image](https://github.com/user-attachments/assets/5e0e3fb5-0089-4cb9-8d27-1a6378b67d09)

**Comment by mssjcksn** [comment]
what are you trying to do @Prets2

**Comment by mssjcksn** [comment]
like nothing renders?

**Comment by Prets2** [comment]
nvm ako ra gi restart ang pc and the app runs now

**Comment by mssjcksn** [comment]
get a new pc
