### ISSUE TITLE
days Regarding the seminar

### ISSUE THREAD

**Issue by Prets2** [ArchonsDev/react-pointwatch-web#78]
i was wondering what if there's a seminar that has multiple days pero dili continous ang days kay i saw maam's swtd she had a seminar nga ang days kay dili continous like she had a seminar at the 17th and 21st day but branded as one seminar
![image](https://github.com/user-attachments/assets/21947aec-f729-44b1-b9af-5ce2a50c7a71)

**Comment by Prets2** [comment]
and could be multiple days not just 2 days ra

**Comment by mssjcksn** [comment]
The user has two options for that matter:
- Submit two separate SWTDs for the different dates
- Submit 1 SWTD. For your example, start date is August 17 and end date is August 21.
These dates don't really matter? It's the total hours that depends on the calculation of the points.
