### ISSUE TITLE
Question lang about sa Proof

### ISSUE THREAD

**Issue by gilberx** [ArchonsDev/react-pointwatch-web#79]
Unsaon nako og add balik og proof if na delete nako accidentally.
![image](https://github.com/user-attachments/assets/347f65b0-7bfc-4ecf-9980-a1533c82c115)
![image](https://github.com/user-attachments/assets/dd309c3b-190d-42d6-844f-6cd77757fa97)

**Comment by mssjcksn** [comment]
😭 noted

**Comment by mssjcksn** [comment]
mag add ra kog button hahahah
