### ISSUE TITLE
SWTD Edit

### ISSUE THREAD

**Issue by gilberx** [ArchonsDev/react-pointwatch-web#81]
Ako ge try og edit ang usa ka for revision nga SWTD niya akong ge change ang Total hours pero ang points wala na ni calculate automatically. Niya after nakog Edit ako ge Save Changes pero ang Status niya "For Revision" gihapon instead of "Pending" (2nd Image).
![image](https://github.com/user-attachments/assets/4fd8d57e-f1c0-4df0-8a27-dc05e7e20831)
![image](https://github.com/user-attachments/assets/40bc87b6-8c47-4c5a-b1f4-97c1d8af6b04)

**Comment by cxrvxxxx** [comment]
Update your backend with the recent commit. And test again. Close this issue if it has been fixed.

**Comment by gilberx** [comment]
Okay brent

**Comment by gilberx** [comment]
Awa Brent same gihapon man. Naka pull nako.
![image](https://github.com/user-attachments/assets/437232a6-a839-4874-8b2e-ac8af1fadd8a)
![image](https://github.com/user-attachments/assets/2bbd1d58-d330-4e84-855e-89693aae17e5)

**Comment by gilberx** [comment]
Fix na thanks
