### ISSUE TITLE
Adding SWTD: College Employee School Year Issue

### ISSUE THREAD

**Issue by gilberx** [ArchonsDev/react-pointwatch-web#84]
So ni create ko og new SWTD sa College Employee pag check nako sa Terms naay School Year:
![image](https://github.com/user-attachments/assets/1200e36a-004b-408e-ad0c-b6bbe44a7c47)

**Comment by mssjcksn** [comment]
di pa updated imo wip badi wa pa nako na push same with #83

**Comment by gilberx** [comment]
awh okayy
