### ISSUE TITLE
Buggy viewing of terms

### ISSUE THREAD

**Issue by Prets2** [ArchonsDev/react-pointwatch-web#91]
This employee account should only be able to see academic years pero usahay manggawas ang mga semester ug ang midyear
![{B87F71BC-2D22-48E8-BE43-BAAD927FABC8}](https://github.com/user-attachments/assets/78580c5b-dffa-4001-9a41-19d7fe4f2036)

**Comment by Prets2** [comment]
but when i restart it it fixes

**Comment by mssjcksn** [comment]
is your branch up to date? @Prets2

**Comment by Prets2** [comment]
this is the deployed one

**Comment by mssjcksn** [comment]
who told you to test the deployed
