### ISSUE TITLE
Updating and Deleting Terms

### ISSUE THREAD

**Issue by gilberx** [ArchonsDev/react-pointwatch-web#92]
Dili ko ka Update og terms og Delete
![image](https://github.com/user-attachments/assets/13716890-aa09-4097-93bf-4e36098acba0)
![image](https://github.com/user-attachments/assets/505cd57d-7d41-482f-9e22-04b96b08aa05)

**Comment by mssjcksn** [comment]
@cxrvxxxx typos again

**Comment by cxrvxxxx** [comment]
Patched, please test again @gilberx

**Comment by Prets2** [comment]
can update terms but cannot delete terms
![{22C90865-56A6-4078-85AC-479BE3DC558B}](https://github.com/user-attachments/assets/bcb5e502-fc75-43ba-9f9a-191b5772feee)

**Comment by Prets2** [comment]
it only states term deleted pero dili mawala ang term

**Comment by cxrvxxxx** [comment]
I tested this now it's fine.
