### ISSUE TITLE
Updating Department

### ISSUE THREAD

**Issue by gilberx** [ArchonsDev/react-pointwatch-web#93]
Di ko ka Update og Department
![image](https://github.com/user-attachments/assets/30397a13-6c90-42f1-a8b8-0aea3cee7486)

**Comment by gilberx** [comment]
![image](https://github.com/user-attachments/assets/5363cf81-2fd3-4c49-8de9-c4fb51f720e0)

**Comment by mssjcksn** [comment]
@cxrvxxxx need diay mo pass og head_id for updating department??

**Comment by cxrvxxxx** [comment]
Patched, please test again @gilberx
