### ISSUE TITLE
Tried creating an account with an existing employee ID

### ISSUE THREAD

**Issue by gilberx** [ArchonsDev/react-pointwatch-web#95]
Tried creating an account with an existing employee ID walay notification ni show nga "Employee ID is already in used chu chu":
![image](https://github.com/user-attachments/assets/9c6a9322-505a-4710-a080-ede23ed7053d)

**Comment by mssjcksn** [comment]
Basin naka comment tong error whatever sa `init.py`?

**Comment by gilberx** [comment]
Okay ako niya e uncomment

**Comment by gilberx** [comment]
Ako nang ge uncomment pero di man gihapon mo gawas ang notification

**Comment by mssjcksn** [comment]
@cxrvxxxx I don't know if your shit is returning any messages?
![image](https://github.com/user-attachments/assets/4ba0ceb2-2497-48d4-bb7d-4889b1c13954)

**Comment by cxrvxxxx** [comment]
Patched. Please test again.

**Comment by gilberx** [comment]
Di gihapon mo gawas ang notification man.
![image](https://github.com/user-attachments/assets/7a33f98b-58a6-4a12-9f4f-afa1e6e06bab)

**Comment by mssjcksn** [comment]
@cxrvxxxx 
![image](https://github.com/user-attachments/assets/0a21951b-cfb8-4ac6-8607-809152d664bd)

**Comment by cxrvxxxx** [comment]
do show api console with enabled & disabled handler

**Comment by mssjcksn** [comment]
> do show api console with enabled & disabled handler

unsa na handler, ktong naas init.py?

**Comment by gilberx** [comment]
Mana goods nani
