### ISSUE TITLE
Head Deleting an Employee's comment

### ISSUE THREAD

**Issue by gilberx** [ArchonsDev/react-pointwatch-web#97]
Diko ka delete og comment sa employee:
![image](https://github.com/user-attachments/assets/8781ff95-341e-4b5b-b844-4385483ac757)
![image](https://github.com/user-attachments/assets/d5ac452c-73cc-4415-8b51-a7d27686a3e2)

**Comment by mssjcksn** [comment]
@cxrvxxxx unsay min auth for deleting of comments?
