### ISSUE TITLE
I tried demoting the head to employee

### ISSUE THREAD

**Issue by gilberx** [ArchonsDev/react-pointwatch-web#98]
Di na ma login ang account:
![image](https://github.com/user-attachments/assets/2ac0cd49-23c8-4802-bd0d-61937ef202f3)
Niya ang promotion page kay sige nag loading:
![image](https://github.com/user-attachments/assets/af9d1096-3efa-495c-949c-2c7a90454382)
Apil sad ang Promotion page sa HR:
![image](https://github.com/user-attachments/assets/596f119e-f6e4-400a-8c7e-97d30c4ba3b2)

**Comment by mssjcksn** [comment]
@gilberx is backend up to date?

**Comment by gilberx** [comment]
Yes

**Comment by mssjcksn** [comment]
> Yes
> 

what happened diay? like ni demote ka nya di ka makalogin after??

**Comment by gilberx** [comment]
Yeah ni demote kog Head then after ana ni loading ra siyag maayu.

**Comment by gilberx** [comment]
I have to remake my database again kay di manjud siya ma okay
